import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { PrismaClient } = require('@prisma/client');
const c = new PrismaClient();
console.log('delegate events:', !!c.events);
console.log('count events :', await c.events.count());
console.log('count profiles:', await c.profiles.count());
console.log('count tickets :', await c.tickets.count());
console.log('count auth_users:', await c.auth_users.count());
const ev = await c.events.findFirst({ select: { id: true, title: true, city: true, status: true, event_start_at: true } });
console.log('exemple event :', JSON.stringify(ev));
const cfg = await c.app_config.findMany({ take: 3 });
console.log('app_config (3) :', JSON.stringify(cfg));
const cpn = await c.coupons.findFirst({ select: { code: true, user_id: true } });
console.log('coupon :', JSON.stringify(cpn));
await c.$disconnect();